// Generated by https://quicktype.io

export interface File {
    mv(uploadPath: any, arg1: (err: any) => void): unknown;
    name:         string;
    data:         Data;
    size:         number;
    encoding:     string;
    tempFilePath: string;
    truncated:    boolean;
    mimetype:     string;
    md5:          string;
}

export interface Data {
    type: string;
    data: any[];
}
